version: "3"

services:
  bookstore-database:
    image: bookstore-database:0.0.1-20220215151046
    networks:
      - bookstore-network
  bookstore-service:
    image: bookstore-service:0.0.1-20220215095505
    networks:
      - bookstore-network
    depends_on:
      - bookstore-database
  bookstore-gateway:
    image: bookstore-gateway:0.0.1-20220215151137
    ports:
      - "443:443"
    networks:
      - bookstore-network
    depends_on:
      - bookstore-service
networks:
  bookstore-network:
    driver: bridge
