version: "3"

services:
  bookstore-database:
    image: bookstore-database:0.0.1-20220214121722
    networks:
      - bookstore-network
  bookstore-service:
    image: bookstore-service:0.0.1-202202140652629
    networks:
      - bookstore-network
    depends_on:
      - bookstore-database
  bookstore-gateway:
    image: bookstore-gateway:0.0.1-20220214162947
    ports:
      - "443:443"
      - "8080:80"
    networks:
      - bookstore-network
    depends_on:
      - bookstore-service
networks:
  bookstore-network:
    driver: bridge
