server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: "classpath:bookstore.p12"
    key-store-password: bookstore
    key-alias: bookstore

security:
  require-ssl: true

graphql:
  specification:
    file: schema.graphqls

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    driverClassName: com.mysql.cj.jdbc.Driver
    username: bookstore
    password: bookstore
    hikari:
      connectionTimeout: 5000
      idleTimeout: 5000
      maxLifetime: 180000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
